"""baseline

Revision ID: 8eaa5ed99d23
Revises: 
Create Date: 2026-07-10 16:21:48.818180
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eaa5ed99d23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_history_id', table_name='sync_history')
    op.drop_table('sync_history')
    op.drop_index('ix_portfolio_snapshots_id', table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_snapshot_date', table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_user_id', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_transactions_executed_at', table_name='transactions')
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_index('ix_transactions_user_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_system_settings_id', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_user_achievements_id', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_achievements_id', table_name='achievements')
    op.drop_table('achievements')
    op.drop_index('ix_user_streaks_id', table_name='user_streaks')
    op.drop_table('user_streaks')
    op.create_index('ix_holdings_user_asset', 'holdings', ['user_id', 'asset_id'], unique=False)
    op.create_index('ix_trades_user_executed', 'trades', ['user_id', 'executed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_user_executed', table_name='trades')
    op.drop_index('ix_holdings_user_asset', table_name='holdings')
    op.create_table('user_streaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('streak_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longest_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_activity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_streaks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_streaks_pkey')
    )
    op.create_index('ix_user_streaks_id', 'user_streaks', ['id'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('achievements_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('achievement_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('requirement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('requirement_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points_reward', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badge_icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='achievements_pkey'),
    sa.UniqueConstraint('achievement_code', name='achievements_achievement_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_achievements_id', 'achievements', ['id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('points_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name='user_achievements_achievement_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_achievements_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_achievements_pkey')
    )
    op.create_index('ix_user_achievements_id', 'user_achievements', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setting_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey'),
    sa.UniqueConstraint('setting_key', name='system_settings_setting_key_key')
    )
    op.create_index('ix_system_settings_id', 'system_settings', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('transaction_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('import_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='transactions_asset_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.create_index('ix_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.create_index('ix_transactions_executed_at', 'transactions', ['executed_at'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('snapshot_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('total_value_usd', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('total_cost_usd', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('total_pnl_usd', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False),
    sa.Column('total_pnl_percentage', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('top_holdings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_assets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='portfolio_snapshots_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='portfolio_snapshots_pkey')
    )
    op.create_index('ix_portfolio_snapshots_user_id', 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_index('ix_portfolio_snapshots_snapshot_date', 'portfolio_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_portfolio_snapshots_id', 'portfolio_snapshots', ['id'], unique=False)
    op.create_table('sync_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trades_synced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transactions_synced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('holdings_updated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sync_history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sync_history_pkey')
    )
    op.create_index('ix_sync_history_id', 'sync_history', ['id'], unique=False)
    # ### end Alembic commands ###
